# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3z36MZeOEllSOoEgQqc2-DXkqds7Mpk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re, nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from wordcloud import WordCloud, STOPWORDS
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/FakeNewsNet.csv')

df.head()

def print_unique_values(col):
    print(f"{col} number of unique values => {df[col].nunique()}")

for col in df.columns:
    print_unique_values(col)

df[df['title'].duplicated()]

df.drop_duplicates(subset='title', keep='last', inplace=True)

df['title'].duplicated().sum()

df['news_url'][0]

df.sample(n=200, random_state=12)[['title', 'news_url', 'real']].iloc[32]

fig, ax = plt.subplots(figsize=(20, 8))
sns.countplot(data=df, x='real', ax=ax)
plt.xticks([0,1], ['False', 'True'])
plt.xlabel('Real', fontsize=20)
plt.show()